import {Request} from './request';

export const dummyActiveVisits = [
  {
    id: 'visit-001',
    service: 'Home Visit - General Checkup',
    status: 'In Progress',
    patientName: 'Abdul Khan',
    patientRelation: 'Father',
    location: '45',
    staffName: 'Rahman Ahmed',
    startedTime: '10:00 AM',
  },
  {
    id: 'visit-002',
    service: 'Home Visit - General Checkup',
    status: 'In Progress',
    patientName: 'Abdul Khan',
    patientRelation: 'Father',
    location: '45',
    staffName: 'Rahman Ahmed',
    startedTime: '10:00 AM',
  },
  {
    id: 'visit-003',
    service: 'Home Visit - General Checkup',
    status: 'In Progress',
    patientName: 'Abdul Khan',
    patientRelation: 'Father',
    location: '45',
    staffName: 'Rahman Ahmed',
    startedTime: '10:00 AM',
  },
];

export const pendingVerificationsData: Request[] = [
  {
    id: '1',
    patient: 'Abdul Rahman',
    relation: 'Father',
    location: 'Dhaka',
    familyMember: '1',
    date: '15 Jan 2026',
    time: '',
    priority: 'Physician Care',
    service: '',
    email: '823@gmail.com',
    phoneNumber: '',
    status: 'active',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: '2',
    patient: 'Fatema Akter',
    relation: 'Mother',
    location: 'Chattogram',
    date: '15 Jan 2026',
    time: '',
    priority: 'Routine Care',
    service: '',
    familyMember: '2',
    email: '213@gmail.com',
    phoneNumber: '43243425235',
    status: 'active',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: '3',
    patient: 'Hasan Mahmud',
    relation: 'Brother',
    location: 'Sylhet',
    date: '16 Jan 2026',
    time: '',
    priority: 'Urgent care',
    service: '',
    familyMember: '3',
    email: '213@gmail.com',
    phoneNumber: '3425343565445',
    status: 'inactive',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: '4',
    patient: 'Nusrat Jahan',
    relation: 'Sister',
    location: 'Rajshahi',
    date: '16 Jan 2026',
    time: '',
    priority: 'Routine Care',
    service: '',
    familyMember: '5',
    email: '213@gmail.com',
    phoneNumber: '56457565656756',
    status: 'inactive',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
];

export const staffData: Request[] = [
  {
    id: 'STF-001',
    patient: 'Dr. Ahsan Rahman',
    relation: 'Senior Doctor',
    location: 'Cardiology',
    date: '18 Jan 2026',
    time: '09:30 AM',
    priority: 'Routine Care',
    email: '@5345345',
    phoneNumber: '4542353425',
    service: '',
    familyMember: '453456346',
    status: 'active',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: 'STF-002',
    patient: 'Nusrat Jahan',
    relation: 'Nurse',
    location: 'Emergency',
    date: '18 Jan 2026',
    time: '10:15 AM',
    priority: 'Routine Care',
    email: '@rh23uirh34',
    phoneNumber: '446565654',
    service: '',
    familyMember: '1',
    status: 'active',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: 'STF-003',
    patient: 'Mahmudul Hasan',
    relation: 'Lab Technician',
    location: 'Pathology',
    date: '18 Jan 2026',
    time: '11:00 AM',
    priority: 'Urgent care',
    email: '@rh23uirh34',
    phoneNumber: '54645643',
    service: '',
    familyMember: '1',
    status: 'inactive',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: 'STF-004',
    patient: 'Dr. Farzana Islam',
    relation: 'Consultant',
    location: 'Gynecology',
    date: '18 Jan 2026',
    time: '01:45 PM',
    priority: 'Routine Care',
    email: '@rh23uirh34',
    phoneNumber: '6645645',
    service: '',
    familyMember: '4',
    status: 'inactive',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
  {
    id: 'STF-005',
    patient: 'Rafiul Karim',
    relation: 'Medical Assistant',
    location: 'Orthopedics',
    date: '18 Jan 2026',
    time: '03:20 PM',
    priority: 'Routine Care',
    email: '@rh23uirh34',
    phoneNumber: '534534656',
    service: '',
    familyMember: '67',
    status: 'active',
    workStatus: 'On Duty',
    age: 0,
    gender: '',
    blood: '',
    lastVisit: '',
    familyMemberCount: undefined,
    name: '',
    role: '',
    specialization: '',
  },
];

export const dummyDashboardData = {
  user: {
    name: 'Emma Wilson',
    role: 'PATIENT',
    avatar: '/avatars/emma.jpg',
  },

  stats: [
    {title: 'Total Requests', value: '3,842', icon: 'Activity'},
    {
      title: 'Next Appointment',
      description: '24 Jan 2026 • 11:15 AM',
      icon: 'Calendar',
    },
    {title: 'Last Visit', value: '12 days ago', icon: 'Clock'},
  ],

  medications: [
    {
      name: 'Metformin 500mg',
      freq: 'Daily (2×)',
      times: 'Morning - Evening',
      patient: 'Father',
      note: null,
    },
    {
      name: 'Amlodipine 5mg',
      freq: 'Daily (1×)',
      times: 'Morning',
      patient: 'Father',
      note: 'BP improved significantly',
    },
    {
      name: 'Atorvastatin 20mg',
      freq: 'Daily (1×)',
      times: 'Evening',
      patient: 'Father',
      note: null,
    },
  ],

  healthScore: {
    value: 82,
    label: 'Good',
    trend: '↑ 4 points this month',
  },

  bloodPressureTrend: [
    {week: 'Week 1', systolic: 148, diastolic: 92},
    {week: 'Week 2', systolic: 145, diastolic: 90},
    {week: 'Week 3', systolic: 142, diastolic: 88},
    {week: 'Week 4', systolic: 138, diastolic: 86},
    {week: 'Week 5', systolic: 134, diastolic: 84},
    {week: 'Week 6', systolic: 130, diastolic: 82},
    {week: 'Week 7', systolic: 128, diastolic: 80},
    {week: 'Week 8', systolic: 124, diastolic: 78},
  ],
};

// ── Dummy data ──
export const carePackages = [
  {
    name: 'Routine Care',
    price: 100,
    desc: 'Regular check-ups and wellness visits',
  },
  {
    name: 'Physician Care',
    price: 2000,
    desc: 'Specialist consultation, treatment plans & follow-ups',
  },
  {
    name: 'Urgent Care',
    price: 4000,
    desc: 'Urgent medical attention for critical cases',
  },
];

export const additionalServices = [
  {name: 'General Consultation', price: 100},
  {name: 'Specialist Consultation', price: 100},
  {name: 'Urgent Care Consultation', price: 100},
  {name: 'Follow-up Consultation', price: 100},
  {name: 'Complete Blood Count (CBC)', price: 100},
  {name: 'Lipid Panel', price: 100},
  {name: 'Blood Glucose', price: 100},
  {name: 'ECG', price: 100},
];
export const userProfileData = [
  {
    id: '1',
    name: 'Abdul Khan',
    relation: 'Father',
    age: 68,
    lastVisit: '3 days ago',
    conditions: 'Type 2 Diabetes and bone issues',
    avatarUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    overallHealthScore: 40,
    lastUpdate: '18 Jan 2026',
    bloodPressure: '142/89',
    bloodGlucose: '112',
    weight: '183 KG',
    birthDay: '18 Jan 2026',
    gender: 'Male',
    blood: 'O+',
    address: 'Dhaka, BD',
    phone: '98534785634763789',
  },
  {
    id: '2',
    name: 'Fatema Begum',
    relation: 'Mother',
    age: 62,
    lastVisit: '1 week ago',
    conditions: 'High blood pressure',
    avatarUrl:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
    overallHealthScore: 55,
    lastUpdate: '15 Jan 2026',
    bloodPressure: '138/85',
    bloodGlucose: '105',
    weight: '165 KG',
    birthDay: '18 Jan 2026',
    gender: 'Female',
    blood: 'O+',
    address: 'Dhaka, BD',
    phone: '98534785634763789',
  },
  {
    id: '3',
    name: 'Rahim Uddin',
    relation: 'Uncle',
    age: 55,
    lastVisit: '2 weeks ago',
    conditions: 'Heart disease',
    avatarUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    overallHealthScore: 50,
    lastUpdate: '10 Jan 2026',
    bloodPressure: '145/90',
    bloodGlucose: '118',
    weight: '172 KG',
    birthDay: '18 Jan 2026',
    gender: 'Male',
    blood: 'O+',
    address: 'Dhaka, BD',
    phone: '98534785634763789',
  },
  {
    id: '4',
    name: 'Ayesha Khan',
    relation: 'Sister',
    age: 32,
    lastVisit: '5 days ago',
    conditions: 'Migraine',
    avatarUrl:
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400',
    overallHealthScore: 78,
    lastUpdate: '20 Jan 2026',
    bloodPressure: '120/80',
    bloodGlucose: '92',
    weight: '130 KG',
    birthDay: '18 Jan 2026',
    gender: 'Female',
    blood: 'O+',
    address: 'Dhaka, BD',
    phone: '98534785634763789',
  },
  {
    id: '5',
    name: 'Imran Hossain',
    relation: 'Brother',
    age: 28,
    lastVisit: '10 days ago',
    conditions: 'Asthma',
    avatarUrl:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400',
    overallHealthScore: 82,
    lastUpdate: '12 Jan 2026',
    bloodPressure: '118/76',
    bloodGlucose: '90',
    weight: '150 KG',
    birthDay: '18 Jan 2026',
    gender: 'Male',
    blood: 'O+',
    address: 'Dhaka, BD',
    phone: '98534785634763789',
  },
  {
    id: '6',
    name: 'Nasima Akter',
    relation: 'Grandmother',
    age: 75,
    lastVisit: '1 month ago',
    conditions: 'Arthritis and vision issues',
    avatarUrl:
      'https://images.unsplash.com/photo-1547425260-76bcadfb4f2d?w=400',
    overallHealthScore: 35,
    lastUpdate: '5 Jan 2026',
    bloodPressure: '150/95',
    bloodGlucose: '130',
    weight: '160 KG',
    birthDay: '18 Jan 2026',
    gender: 'Female',
    blood: 'O+',
    address: 'Dhaka, BD',
    phone: '98534785634763789',
  },
];

export const userData = {
  name: 'Emma Watson',
  status: 'active',
  email: 'emma.watson@email.com',
  phone: '+44 20 7946 0958',
  location: 'House 56',
  country: 'United Kingdom',
  joined: 'Jan 4, 2026',
  profileCount: 3,
  profiles: [
    {
      id: 1,
      name: 'Emma Watson',
      relation: 'Self',
      age: 34,
      gender: 'Female',
      blood: 'A+',
      lastVisit: 'Jan 2, 2026',
    },
    {
      id: 2,
      name: 'Olivia Watson',
      relation: 'Daughter',
      age: 8,
      gender: 'Female',
      blood: 'O+',
      lastVisit: 'Dec 28, 2025',
    },
    {
      id: 3,
      name: 'James Watson',
      relation: 'Son',
      age: 5,
      gender: 'Male',
      blood: 'A+',
      lastVisit: 'Dec 15, 2025',
    },
  ],
};

export const users = [
  {
    id: 1,
    name: 'Harry',
    relation: 'Son',
    age: 32,
    avatar:
      'https://media.istockphoto.com/id/2149530993/photo/digital-human-head-concept-for-ai-metaverse-and-facial-recognition-technology.jpg?s=1024x1024&w=is&k=20&c=Ob0ACggwWuFDFRgIc-SM5bLWjNbIyoREeulmLN8dhLs=',
  },
  {
    id: 2,
    name: 'Sana Khan',
    relation: 'Mom',
    age: 55,
    avatar:
      'https://media.istockphoto.com/id/1310488699/photo/abstract-technological-background-in-vibrant-colors-with-blur.jpg?s=1024x1024&w=is&k=20&c=DJijfv9leMdb7zhS0ntBm6Ekr7KpId19xAIpK53U-K4=',
  },
];

// data/jobs.ts
export type Job = {
  id: string;
  title: string;
  subtitle: string;
  status?: string;
  location?: string;
  type?: string; // Full-time, Part-time, Contract, etc.
  description?: string;
  responsibilities: string[];
  requirements: string[];
};

export const jobs: Job[] = [
  {
    id: 'care-coordinator',
    title: 'Care Coordinator',
    subtitle: 'Remote/Hybrid • Full-time or Part-time',
    status: 'Open',
    location: 'Remote / Hybrid (Bangladesh preferred)',
    type: 'Full-time / Part-time',
    description:
      'Help families by coordinating appointments, referrals, follow-ups, and updates.',
    responsibilities: [
      'Manage inbound requests and coordinate next steps across providers, partners, and family members',
      'Schedule appointments, referrals, labs/diagnostics, and care follow-ups with clear confirmation',
      'Coordinate home/mobile visit logistics (routing, prep, supplies, patient readiness, time windows)',
      'Maintain clear documentation and provide proactive updates to families (closed-loop communication)',
      'Use checklists and playbooks to ensure consistent, high-quality coordination and handoffs',
      'Escalate time-sensitive issues per protocol and track them through resolution',
    ],
    requirements: [
      'Experience in care coordination, patient navigation, clinical operations, or member services',
      'Strong communication skills (written and verbal) and high attention to detail',
      'Ability to juggle multiple cases, priorities, and follow-ups without dropping handoffs',
      'Comfort handling sensitive information',
      'Empathy and calm judgment when supporting families in stressful moments',
    ],
  },
  // Add other jobs similarly...
  {
    id: 'rn-nurse',
    title: 'RN / Nurse',
    subtitle: 'Hybrid/Field • Contract or Part-time • On-call options',
    status: 'Open',
    responsibilities: [],
    requirements: [],
  },
  // etc.
];
